plugins:
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4

# I keep the length as short as possible without having too much pain.
# 80 is too much pain, but many disagree.
Layout/LineLength:
  Max: 100

# Automatically add frozen string safety comments.
Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

# Don't accidentally delete `focus` while developing.
Minitest/Focus:
  SafeAutoCorrect: false

# # Tests may have long blocks.
Metrics/AbcSize:
  Exclude:
    - '**/test/**/*_test.rb'
Metrics/BlockLength:
  Exclude:
    - '**/test/**/*_test.rb'
Metrics/MethodLength:
  Exclude:
    - '**/test/**/*_test.rb'

Layout/LineLength:
  Exclude:
    - '**/test/**/*_test.rb'

Minitest/MultipleAssertions:
  Exclude:
    - '**/test/**/*_test.rb'
