# frozen_string_literal: true

require 'base64'
require 'bigdecimal'
require 'calls'
require 'csv'
require 'json'
require 'logger'
require 'securerandom'
require 'tmpdir'
require 'tron'

require 'datanorm/logger'
require 'datanorm/logging'
require 'datanorm/helpers/utf8'
require 'datanorm/helpers/filename'

require 'datanorm/headers/v4/date'
require 'datanorm/headers/v4/title'
require 'datanorm/headers/v4/version'
require 'datanorm/headers/v5/date'
require 'datanorm/headers/v5/title'
require 'datanorm/headers/v5/version'

require 'datanorm/lines/parse'
require 'datanorm/lines/base'
require 'datanorm/lines/v4/product'
require 'datanorm/lines/v4/extra'
require 'datanorm/lines/v4/priceset'
require 'datanorm/lines/v4/price'
require 'datanorm/lines/v4/dimension'
require 'datanorm/lines/v4/text'
require 'datanorm/lines/v5/product'
require 'datanorm/lines/v5/price'
require 'datanorm/lines/v5/text'
require 'datanorm/lines/v5/dimension'

require 'datanorm/lines/v4/parse'
require 'datanorm/lines/v5/parse'

require 'datanorm/documents/preprocess'
require 'datanorm/documents/preprocesses/cache'
require 'datanorm/documents/preprocesses/process'
require 'datanorm/documents/assembles/product'
require 'datanorm/documents/assembles/price'
require 'datanorm/documents/assembles/reference'
require 'datanorm/documents/assemble'
require 'datanorm/progress'
require 'datanorm/document'
require 'datanorm/file'
require 'datanorm/header'
require 'datanorm/version'
